baseURL: "https://atchisontechnology.com/"
title: "Atchison Technology LLC"
theme: "hugo-universal-theme"
languageCode: "en-us"
defaultContentLanguage: "en"
googleAnalytics: ""
paginate: 10
# enableInlineShortcodes: true
params:
    style: "blue"
    logo: "img/logo.png"
    logo_small: "img/logo-small.png"
    date_format: "January 2, 2006"
    # viewMorePostLink: "/blog/"
    author: "Lee Atchison"
    defaultKeywords: ["cloud","digital transformation","cloud migration","application modernization","devops"]
    # mainSections: ["blog"]
    defaultDescription: "Lee Atchison provides consulting and advising to enterprises on cloud computing, application modernization, digital transformation, application scaling, and maintaining high availability."
    about_us: "<p>Lee Atchison provides consulting and advising to enterprises on cloud computing, application modernization, digital transformation, application scaling, and maintaining high availability.</p>"
    address: >
        <p class="text-uppercase"><strong>Atchison Technology LLC</strong>
        <br>1037 NE 65th St #81899
        <br>Seattle, WA 98115
        <br><i>United States of America</i>
        </p>
    copyright: "Copyright © 2020, Atchison Technology LLC; all rights reserved."
    # Social media
    facebook_site: "mdascale" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site: "leeatchison" # the Twitter handle of your site (without the '@')
    default_sharing_image: "img/sharing-default.png"
    carousel:
        enable: true
    features:
        enable: true
    testimonials:
        enable: true
        title: "Testimonials"
        subtitle: "Listen to some comments from the folks who have worked with Lee over the years."
    see_more:
        enable: true
        icon: "far fa-file-alt"
        title: "Do you want to learn more?"
        subtitle: "Please contact us for more details."
        link_url: "contact"
        link_text: "Contact Us"
    clients:
        enable: false
        title: "Our Clients"
        subtitle: ""
    recent_posts:
        enable: false
        title: "From our blog"
        subtitle: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps: false
    googleMapsApiKey: ""
    # latitude: "-12.043333"
    # longitude: "-77.028333"
    # # Enable and disable widgets for the right sidebar
    widgets:
        categories: true
        tags: true
        search: true
    topbar:
        enable: true
        text: >
            <p class="hidden-sm hidden-xs">
            Contact us for an overview and evaluation.
            <a href="/contact" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
            </p>
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
    main:
        -   identifier: home
            name: "Home"
            url : "/"
            weight: 1
        -   identifier: whoislee
            name: "Who is Lee?"
            url: "/whoislee"
            weight: 2
        # -   identifier: calendar
        #     name: "Schedule a Meeting"
        #     url: "/calendar"
        #     weight: 3
        -   identifier: contact
            name: "Contact"
            url: "/contact"
            weight: 4
    topbar:
        -   weight: 1
            name: LinkedIn
            url: "https://www.linkedin.com/in/leeatchison/"
            pre: <i class='fab fa-2x fa-linkedin'></i>
        -   weight: 2
            name: Twitter
            url: "https://twitter.com/leeatchison"
            pre: <i class='fab fa-2x fa-twitter'></i>
        -   weight: 3
            name: Facebook
            url: "https://www.facebook.com/mdascale"
            pre: <i class='fab fa-2x fa-facebook'></i>
        -   weight: 4
            name: Email
            url: "mailto:intro@atchisontechnology.com"
            pre: <i class='fas fa-2x fa-envelope'></i>
