baseURL: "https://atchisontechnology.com/"
title: "Atchison Technology LLC | Modernize Your Enterprise - Thoughtful, advice from an external point of view"
theme: "bexar-hugo"
params:
  logo: "images/at_logo.png"
  logo_footer: "images/at_logo.png"
  description: "Many corporate leaders are facing stagnant revenue and unhappy staff. I advise leaders on how to modernize their environment to make customers happier and staff energized for growth and success."
  author: "Lee Atchison"
  address: "1037 NE 65th St #81899, Seattle, WA 98115"
  mobile: "+1(360)670-0674‬"
  email: "info@atchisontechnology.com"
  contact_form_action: "#" # TODO: contact form works with https://formspree.io
  google_analitycs_id: "UA-173525449-1"
  search: true
  top_header: false
  navigation_button:
    enable: true
    label: "Schedule a Call"
    link: "/contact"
  social:
    - icon: "fa-linkedin"
      link: "https://www.linkedin.com/in/leeatchison/"
    - icon: "fa-twitter"
      link: "https://twitter.com/leeatchison"
    - icon: "fa-facebook"
      link: "https://www.facebook.com/mdascale"
    - icon: "fa-envelope"
      link: "/subscribe/"


  preloader:
    enable: true
    preloader: "images/preloader.gif"
  plugins:
    css:
      - link: "plugins/bootstrap/bootstrap.min.css"
      - link: "plugins/slick/slick.css"
      - link: "plugins/fontawesome/font-awesome.min.css"
      - link: "plugins/animate/animate.css"
      - link: "plugins/venobox/venobox.css"
    js:
      - link: "plugins/jQuery/jquery.min.js"
      - link: "plugins/bootstrap/bootstrap.min.js"
      - link: "plugins/slick/slick.min.js"
      - link: "plugins/google-map/gmap.js"
      - link: "plugins/venobox/venobox.min.js"
      - link: "plugins/filterizr/jquery.filterizr.min.js"
      - link: "plugins/search/fuse.min.js"
      - link: "plugins/search/mark.js"
      - link: "plugins/search/search.js"

menu:
  main:
    - name: "Who is Lee?"
      URL: "/whoislee/"
      weight: 1
    # - name: "Services"
    #   URL: "/service"
    #   weight: 2
    - name: "About Us"
      URL: "/about"
      weight: 3
  footer:
    - name: "Who is Lee?"
      URL: "/whoislee/"
      weight: 1
    - name: "Subscribe"
      URL: "/subscribe"
      weight: 2
    - name: "Privacy Policy"
      URL: "/privacy"
      weight: 3

languages:
  en:
    languageName: "En"
    languageCode: "en-us"
    contentDir: "content/english"
    weight: 1
    home: "Home"
    footer_content: >
      Lee Atchison advises leaders 
      facing stagnant revenue and unhappy staff
      on how to 
      modernize their environment to make customers 
      happier and staff energized for growth and success.
    copyright: >
      Copyright &copy; 2020 [Lee Atchison](https://leeatchison.com)
