baseURL: "https://atchisontechnology.com/"
title: "Atchison Technology LLC"
theme: "hugo-universal-theme"
languageCode: "en-us"
defaultContentLanguage: "en"
googleAnalytics: ""
paginate: 10
params:
    style: "blue"
    logo: "img/logo.png"
    logo_small: "img/logo-small.png"
    # viewMorePostLink: "/blog/"
    # author: "Lee Atchison"
    # defaultKeywords: ["devows", "hugo", "go"]
    # mainSections: ["blog"]
    # defaultDescription: "Site template made by devcows using hugo"
    # about_us: "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
    copyright: "Copyright © 2020, Atchison Technology LLC; all rights reserved."
    # Social media
    facebook_site: "mdascale" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site: "leeatchison" # the Twitter handle of your site (without the '@')
    default_sharing_image: "img/sharing-default.png"
    carousel:
        enable: true
    features:
        enable: true
    testimonials:
        enable: true
        title: "Testimonials"
        subtitle: "Listen to some comments from the folks who have worked with Lee over the years."
    see_more:
        enable: true
        icon: "far fa-file-alt"
        title: "Do you want to learn more?"
        subtitle: "Please contact us for more details."
        link_url: "contact"
        link_text: "Contact Us"
    # clients:
    #     enable: false
    #     title: "Our Clients"
    #     subtitle: ""
    # recent_posts:
    #     enable: false
    #     title: "From our blog"
    #     subtitle: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    # # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    # enableGoogleMaps: false
    # googleMapsApiKey: ""
    # # latitude: "-12.043333"
    # # longitude: "-77.028333"
    topbar:
        enable: true
        text: >
            <p class="hidden-sm hidden-xs">
            Contact us for an overview and evaluation.
            <a href="mailto:intro@atchisontechnology.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
            </p>
menu:
    main:
        -   identifier: home
            name: "Home"
            url : "/"
            weight: 1
        -   identifier: about
            name: "About"
            url: "/"
            weight: 2
    topbar:
        -   weight: 1
            name: LinkedIn
            url: "https://www.linkedin.com/in/leeatchison/"
            pre: <i class='fab fa-2x fa-linkedin'></i>
        -   weight: 2
            name: Twitter
            url: "https://twitter.com/leeatchison"
            pre: <i class='fab fa-2x fa-twitter'></i>
        -   weight: 3
            name: Facebook
            url: "https://www.facebook.com/mdascale"
            pre: <i class='fab fa-2x fa-facebook'></i>
        -   weight: 4
            name: Email
            url: "mailto:intro@atchisontechnology.com"
            pre: <i class='fas fa-2x fa-envelope'></i>

# [[menu.topbar]]
#     weight = 2
#     name = "Facebook"
#     url = "http://facebook.com"
#     pre = "<i class='fab fa-2x fa-facebook'></i>"

# [[menu.topbar]]
#     weight = 3
#     name = "Twitter"
#     url = "http://twitter.com"
#     pre = "<i class='fab fa-2x fa-twitter'></i>"

# [[menu.topbar]]
#     weight = 4
#     name = "Email"
#     url = "mailto:your@email.com"
#     pre = "<i class='fas fa-2x fa-envelope'></i>"




# #
# #
# # System Parameters
# #
# #
# [params]
#     # Since this template is static, the contact form uses www.formspree.io as a
#     # proxy. The form makes a POST request to their servers to send the actual
#     # email. Visitors can send up to a 1000 emails each month for free.
#     #
#     # What you need to do for the setup?
#     #
#     # - set your email address under 'email' below
#     # - upload the generated site to your server
#     # - send a dummy email yourself to confirm your account
#     # - click the confirm link in the email from www.formspree.io
#     # - you're done. Happy mailing!
#     #
#     # Enable the contact form by entering your Formspree.io email
#     email = "your@email.com"
#     contact_form_ajax = false


#     # Format dates with Go's time formatting
#     date_format = "January 2, 2006"

#     logo = "img/logo.png"
#     logo_small = "img/logo-small.png"
#     address = """<p class="text-uppercase"><strong>Universal Ltd.</strong>
#         <br>13/25 New Avenue
#         <br>Newtown upon River
#         <br>45Y 73J
#         <br>England
#         <br>
#         <strong>Great Britain</strong>
#       </p>
#       """

# # Enable or disable top bar with social icons

# # Enable and disable widgets for the right sidebar
# [params.widgets]
#     categories = true
#     tags = true
#     search = true

    

# # [Permalinks]
# #     blog = "/blog/:year/:month/:day/:filename/"


# #
# #
# # Menus
# #
# #
# [[menu.main]]
#     identifier="home"
#     name = "Home"
#     url  = "/"
#     weight = 1

# [[menu.main]]
#     identifier="blog"
#     name = "Blog"
#     url  = "/blog/"
#     weight = 2

# [[menu.main]]
#     identifier = "faq"
#     name = "FAQ"
#     url  = "/faq/"
#     weight = 3

# [[menu.main]]
#     identifier = "contact"
#     name = "Contact"
#     url  = "/contact/"
#     weight = 4

# # Top bar social links menu


