---
baseURL: https://atchisontechnology.com/
title: Atchison Technology LLC
theme: hugo-universal-theme
languageCode: en-us
defaultContentLanguage: en
googleAnalytics: ''
paginate: '10'
params:
  style: blue
  logo: img/logo.png
  logo_small: img/logo-small.png
  date_format: January 2, 2006
  author: Lee Atchison
  defaultKeywords:
  - cloud
  - digital transformation
  - cloud migration
  - application modernization
  - devops
  defaultDescription: Lee Atchison provides consulting and advising to enterprises
    on cloud computing, application modernization, digital transformation, application
    scaling, and maintaining high availability.
  about_us: "<p>Lee Atchison provides consulting and advising to enterprises on cloud
    computing, application modernization, digital transformation, application scaling,
    and maintaining high availability.</p>"
  address: '<p class="text-uppercase"><strong>Atchison Technology LLC</strong> <br>1037
    NE 65th St #81899 <br>Seattle, WA 98115 <br><i>United States of America</i> </p>

'
  copyright: Copyright © 2020, Atchison Technology LLC; all rights reserved.
  facebook_site: mdascale
  twitter_site: leeatchison
  default_sharing_image: img/sharing-default.png
  carousel:
    enable: true
  features:
    enable: true
  testimonials:
    enable: true
    title: Testimonials
    subtitle: Listen to some comments from the folks who have worked with Lee over
      the years.
  see_more:
    enable: true
    icon: far fa-file-alt
    title: Do you want to learn more?
    subtitle: Please contact us for more details.
    link_url: contact
    link_text: Contact Us
  clients:
    enable: false
    title: Our Clients
    subtitle: ''
  recent_posts:
    enable: false
    title: From our blog
    subtitle: Pellentesque habitant morbi tristique senectus et netus et malesuada
      fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget,
      tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean
      ultricies mi vitae est. Mauris placerat eleifend leo.
  enableGoogleMaps: false
  googleMapsApiKey: ''
  widgets:
    categories: true
    tags: true
    search: true
  topbar:
    enable: true
    text: '<p class="hidden-sm hidden-xs"> Contact us for an overview and evaluation.
      <a href="/contact" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>

'
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  topbar:
  - pre: "<i class='fab fa-2x fa-linkedin'></i>"
    url: https://www.linkedin.com/in/leeatchison/
    name: LinkedIn
    weight: 1
  - pre: "<i class='fab fa-2x fa-twitter'></i>"
    url: https://twitter.com/leeatchison
    name: Twitter
    weight: 2
  - pre: "<i class='fab fa-2x fa-facebook'></i>"
    url: https://www.facebook.com/mdascale
    name: Facebook
    weight: 3
  - pre: "<i class='fas fa-2x fa-envelope'></i>"
    url: mailto:intro@atchisontechnology.com
    name: Email
    weight: 4
